### ISSUE TITLE
1.5: setuptools build_sphinx command does not work with sphinx 4.0.x

### ISSUE THREAD

**Issue by kloczek** [dabeaz/curio#343]
```console
+ /usr/bin/python3 setup.py build_sphinx -b man
running build_sphinx
Running Sphinx v4.0.2

Extension error:
Could not import extension customization (exception: cannot import name 'PyModulelevel' from 'sphinx.domains.python' (/usr/lib/python3.8/site-packages/sphinx/domains/python.py))
```
